
POST http://localhost:8000/register HTTP/1.1
Content-Type: application/json

{
    "name": "vikash",
    "username": "vikash",
    "email": "vikash@example.com",
    "password": "12345"
}

###

POST http://localhost:8000/login HTTP/1.1
Content-Type: application/json

{
    "email": "vikash@example.com",
    "password": "12345"
}

###

GET  http://localhost:8000/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
"token": "c73a0885da150a196396f1130ec063101142a8f25f55a6a094a261f9bbf93a80"
}


###
POST http://localhost:8000/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token": "c73a0885da150a196396f1130ec063101142a8f25f55a6a094a261f9bbf93a80",
    "bio" : "hi im a mern stack developer with 2 years of experience in building web applications.",
     "currentPost": "Software Engineer",
    "pastWork" : [
        {
            "company": "ABC Company",
            "position": "Software Engineer",
            "years": "2 years"
        }
    ],
    "education" : [
        {
            "school": "University of BBD",
            "degree": "Bachelor of Science",
            "fieldOfStudy": "Computer Science"
        }
    ]


}

###

GET http://localhost:8000/get_all_user_profiles HTTP/1.1
Content-Type: application/json




